# Generated by Django 5.1.5

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("salary", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(choices=[("USD", "US Dollar ($)"), ("AFN", "Afghan Afghani (؋)")], default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("module", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["module", "name"],
            },
        ),
        migrations.CreateModel(
            name="Advance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(choices=[("USD", "US Dollar ($)"), ("AFN", "Afghan Afghani (؋)")], default="USD", max_length=3)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.CharField(max_length=20)),
                ("payment_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="advances", to="api.employee")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("expense_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("currency", models.CharField(choices=[("USD", "US Dollar ($)"), ("AFN", "Afghan Afghani (؋)")], default="USD", max_length=3)),
                ("receipt", models.FileField(blank=True, null=True, upload_to="expenses/receipts/")),
                ("description", models.TextField(blank=True, null=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="expenses", to=settings.AUTH_USER_MODEL)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="api.expensecategory")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("month", models.CharField(max_length=20)),
                ("year", models.PositiveIntegerField()),
                ("salary", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(choices=[("USD", "US Dollar ($)"), ("AFN", "Afghan Afghani (؋)")], default="USD", max_length=3)),
                ("payment_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payrolls", to="api.employee")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("action", models.CharField(choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete"), ("login", "Login"), ("logout", "Logout"), ("view", "View"), ("export", "Export"), ("payment", "Payment")], max_length=20)),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("content_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="contenttypes.contenttype")),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activity_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="api_activit_created_011954_idx"),
                    models.Index(fields=["user", "-created_at"], name="api_activit_user_id_29f0f8_idx"),
                    models.Index(fields=["action", "-created_at"], name="api_activit_action_35dd86_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("granted", models.BooleanField(default=True)),
                ("permission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.permission")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_permissions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "permission")},
            },
        ),
    ]