# Generated by Django 5.1.5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # AccountCategory
        migrations.CreateModel(
            name="AccountCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("account_type", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        # Account
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_detail", models.BooleanField(default=True)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="accounts", to="api.accountcategory")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="api.account")),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        # Transaction
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("number", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("transaction_type", models.CharField(default="journal", max_length=20)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("is_posted", models.BooleanField(default=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        # JournalEntry
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("date", models.DateField()),
                ("debit", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("credit", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("description", models.TextField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="journal_entries", to="api.account")),
                ("transaction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="api.transaction")),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        # FiscalYear
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        # StudentCategory
        migrations.CreateModel(
            name="StudentCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        # Student
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("full_name", models.CharField(max_length=200)),
                ("father_name", models.CharField(max_length=200)),
                ("grandfather_name", models.CharField(blank=True, max_length=200, null=True)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(default="male", max_length=20)),
                ("tazkira_number", models.CharField(max_length=50, unique=True)),
                ("permanent_address", models.TextField()),
                ("current_address", models.TextField()),
                ("province", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("parent_phone", models.CharField(max_length=20)),
                ("student_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("alternative_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, null=True)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("registration_date", models.DateField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="active", max_length=20)),
                ("transportation", models.CharField(default="school_bus", max_length=20)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="students/photos/")),
                ("tazkira_copy", models.FileField(blank=True, null=True, upload_to="students/tazkira/")),
                ("parent_tazkira_copy", models.FileField(blank=True, null=True, upload_to="students/parent_tazkira/")),
                ("previous_result_card", models.FileField(blank=True, null=True, upload_to="students/results/")),
                ("payment_receipt", models.FileField(blank=True, null=True, upload_to="students/receipts/")),
                ("category", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="students", to="api.studentcategory")),
            ],
            options={
                "ordering": ["-registration_date"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        # StudentPayment
        migrations.CreateModel(
            name="StudentPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                ("payment_method", models.CharField(default="cash", max_length=50)),
                ("reference_number", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("receipt", models.FileField(blank=True, null=True, upload_to="student_payments/receipts/")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="api.student")),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        # ShopStatus
        migrations.CreateModel(
            name="ShopStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        # Shop
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("shop_number", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("area", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("monthly_rent", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("status", models.CharField(default="available", max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["shop_number"],
            },
        ),
        # Tenant
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("tazkira_number", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        # ShopRental
        migrations.CreateModel(
            name="ShopRental",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("monthly_rent", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("rental_status", models.CharField(default="active", max_length=20)),
                ("security_deposit", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("description", models.TextField(blank=True, null=True)),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rentals", to="api.shop")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rentals", to="api.tenant")),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        # IncomeCategory
        migrations.CreateModel(
            name="IncomeCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("category_type", models.CharField(default="other", max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        # OtherIncome
        migrations.CreateModel(
            name="OtherIncome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("income_date", models.DateField(default=django.utils.timezone.now)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("receipt", models.FileField(blank=True, null=True, upload_to="other_income/receipts/")),
                ("income_category", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incomes", to="api.incomecategory")),
            ],
            options={
                "ordering": ["-income_date"],
            },
        ),
    ]