# Generated by Django 5.1.5 on 2026-05-15 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_accounting_student_shop_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('registration', 'Registration Fee'), ('monthly', 'Monthly Fee'), ('multi_month', 'Multi-Month Package'), ('transport', 'Transportation Fee'), ('other', 'Other Fee')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('AFN', 'Afghan Afghani (؋)')], default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('AFN', 'Afghan Afghani (؋)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_detail',
            field=models.BooleanField(default=True, help_text='Can post entries to this account'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='account_type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='advance',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='category_type',
            field=models.CharField(choices=[('service', 'Service Income'), ('miscellaneous', 'Miscellaneous'), ('business', 'Business Income'), ('investment', 'Investment Income'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('AFN', 'Afghan Afghani (؋)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shop',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('AFN', 'Afghan Afghani (؋)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='shoprental',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('AFN', 'Afghan Afghani (؋)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='shoprental',
            name='rental_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('renewed', 'Renewed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('transferred', 'Transferred')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='transportation',
            field=models.CharField(choices=[('school_bus', 'School Bus'), ('private_vehicle', 'Private Vehicle'), ('walking', 'Walking'), ('public_transport', 'Public Transport')], default='school_bus', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('AFN', 'Afghan Afghani (؋)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('student_payment', 'Student Payment'), ('expense', 'Expense'), ('payroll', 'Payroll'), ('advance', 'Advance Salary'), ('rental_income', 'Rental Income'), ('other_income', 'Other Income'), ('journal', 'Manual Journal Entry'), ('opening', 'Opening Balance')], default='journal', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otherincome',
            index=models.Index(fields=['income_date'], name='api_otherin_income__bc1973_idx'),
        ),
        migrations.AddIndex(
            model_name='otherincome',
            index=models.Index(fields=['income_category'], name='api_otherin_income__bb5e66_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registration_number'], name='api_student_registr_9b45b2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tazkira_number'], name='api_student_tazkira_b35c54_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='api_student_status_8ed2d4_idx'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.paymentcategory'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['student', 'payment_date'], name='api_student_student_6bbf0e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['payment_status'], name='api_student_payment_82f370_idx'),
        ),
    ]
