# Generated by Django 5.1.5 on 2026-05-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_classlevel_student_payment_cycle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='api_student_class_l_fea202_idx',
            old_name='api_student_class_e6be54_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='api_student_payment_0ddba4_idx',
            old_name='api_student_payment__14e16a_idx',
        ),
        migrations.RenameIndex(
            model_name='studentpayment',
            new_name='api_student_payment_766a95_idx',
            old_name='api_stud_payment__83478a_idx',
        ),
        migrations.RenameIndex(
            model_name='studentpayment',
            new_name='api_student_period__d1322e_idx',
            old_name='api_stud_period__109a5b_idx',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_level',
            field=models.ForeignKey(blank=True, help_text='Class level the student is enrolled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.classlevel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Payment frequency: monthly or yearly', max_length=10),
        ),
    ]
